### ISSUE TITLE
Slovenië in Dutch is Solvenië on web

### ISSUE THREAD

**Issue by ikiv** [rydoo/translations-Typos#2]
![schermafbeelding 2018-07-09 om 14 43 17](https://user-images.githubusercontent.com/10089600/42455521-c3d21360-8392-11e8-8a3c-5e4e5c78e9f0.png)

**Comment by ikiv** [comment]
doesn't really work when your search for Slovenië :-)

**Comment by kasperexp** [comment]
Solved
