### ISSUE TITLE
When choosing a country in personal settings in Dutch it should say 'Griekenland' not 'Griekeland'

### ISSUE THREAD

**Issue by janschouteet** [rydoo/translations-Typos#5]
When choosing a country in personal settings in Dutch it should say 'Griekenland' not 'Griekeland'.
Many thanks for editing this whenever you have the time.
![snip20181026_131](https://user-images.githubusercontent.com/43538621/47572798-1ea20580-d93c-11e8-99fc-660816de0f8a.png)

**Comment by kasperexp** [comment]
Solved
